(function(){
"use strict";
const $=id=>document.getElementById(id),esc=PTLC.esc,n=PTLC.n,money=PTLC.money;
const pct=v=>Number.isFinite(Number(v))?(Number(v)*100).toFixed(1)+"%":"—";
const dateFmt=s=>{if(!s)return"—";const d=new Date(s+"T00:00:00");return isNaN(d)?"—":d.toLocaleDateString("ar-OM",{year:"numeric",month:"2-digit",day:"2-digit"})};
const daysLeft=s=>{if(!s)return null;const end=new Date(s+"T00:00:00"),now=new Date();now.setHours(0,0,0,0);return Math.ceil((end-now)/86400000)};
const row=(label,plan,actual,unit)=>{const p=Number(plan),a=Number(actual),has=Number.isFinite(p)&&p>0&&Number.isFinite(a),ok=has&&a>=p,delta=has?a-p:null;const fmt=v=>unit==="%"?pct(v):unit==="count"?n(v).toLocaleString("en-US"):money(v);return"<tr><td>"+esc(label)+"</td><td>"+(Number.isFinite(p)&&p>0?fmt(p):"—")+"</td><td class='actual'>"+(Number.isFinite(a)?fmt(a):"—")+"</td><td class='delta'>"+(delta===null?"—":fmt(delta))+"</td><td>"+(has?'<span class="'+(ok?"state-ok":"state-bad")+'">'+(ok?"✓ محقق":"✕ غير محقق")+"</span>":'<span class="state-neutral">لا توجد خطة</span>')+"</td></tr>"};
async function safe(path,fallback=[]){try{return await PTLC.api(path)}catch(e){return fallback}}
function latest(rows){if(!rows.length)return[];const max=Math.max(...rows.map(r=>Number(r.year_no||0)*4+Number(r.quarter_no||0)));return rows.filter(r=>Number(r.year_no||0)*4+Number(r.quarter_no||0)===max)}
async function load(){
 const id=new URLSearchParams(location.search).get("id");if(!id)throw Error("لم يتم تحديد المشروع.");
 const p=(await PTLC.api("/projects?id=eq."+encodeURIComponent(id)+"&select=*"))[0];if(!p)throw Error("المشروع غير موجود.");
 const [en,co,st,pr,pl,re]=await Promise.all([safe("/government_entities?id=eq."+encodeURIComponent(p.government_entity_id)+"&select=id,name"),p.company_id?safe("/companies?id=eq."+encodeURIComponent(p.company_id)+"&select=id,name"):Promise.resolve([]),safe("/excel_import_staging?batch_name=eq."+encodeURIComponent("المشاريع(4).xlsx")+"&select=source_row,payload&order=source_row.asc"),safe("/project_results?project_id=eq."+encodeURIComponent(id)+"&select=*"),safe("/local_content_plans?project_id=eq."+encodeURIComponent(id)+"&select=*&order=created_at.desc"),safe("/quarterly_reports?project_id=eq."+encodeURIComponent(id)+"&select=*&order=year_no.desc,quarter_no.desc,created_at.desc")]);
 const entity=en[0],company=co[0],payload=(st||[]).map(x=>x.payload||{}).find(x=>String(x["اسم المشروع"]||"")===String(p.project_name||""))||{},actual=pr[0]||{},plan=pl[0]||null;
 const [pw,ps,pp,psv,psub]=await Promise.all([plan?safe("/plan_workforce?plan_id=eq."+plan.id+"&select=*"):Promise.resolve([]),plan?safe("/plan_salaries?plan_id=eq."+plan.id+"&select=*"):Promise.resolve([]),plan?safe("/plan_purchases?plan_id=eq."+plan.id+"&select=*"):Promise.resolve([]),plan?safe("/plan_services?plan_id=eq."+plan.id+"&select=*"):Promise.resolve([]),plan?safe("/plan_subcontracts?plan_id=eq."+plan.id+"&select=*"):Promise.resolve([])]);
 const lw=latest(pw),planO=lw.reduce((s,r)=>s+n(r.omani_count),0),planF=lw.reduce((s,r)=>s+n(r.foreign_count),0),planOman=planO+planF?planO/(planO+planF):0,planOS=ps.reduce((s,r)=>s+n(r.omani_salary),0),planFS=ps.reduce((s,r)=>s+n(r.foreign_salary),0),planPurch=pp.reduce((s,r)=>s+n(r.total_value),0),planServ=psv.reduce((s,r)=>s+n(r.total_value),0),planSub=psub.reduce((s,r)=>s+n(r.total_value),0),smeValue=psv.filter(r=>String(r.supplier_type||"").includes("صغيرة")||String(r.supplier_type||"").includes("متوسطة")).reduce((s,r)=>s+n(r.total_value),0)+psub.filter(r=>String(r.supplier_type||"").includes("صغيرة")||String(r.supplier_type||"").includes("متوسطة")).reduce((s,r)=>s+n(r.total_value),0),planSME=p.project_value?smeValue/n(p.project_value):0;
 const actualO=n(actual.cumulative_omani_count)||n(payload["عدد العمانيين حاليا"]),actualF=n(actual.cumulative_foreign_count)||n(payload["عدد الاجانب حاليا"]),actualOman=actual.omanization_percent??(payload["نسبة التعمين"]??(actualO+actualF?actualO/(actualO+actualF):0)),actualOS=n(actual.omani_salary_actual)||n(payload["اجمالي تكلفة رواتب العمانيين"]),actualFS=n(actual.foreign_salary_actual)||n(payload["اجمالي تكلفة رواتب الاجانب"]),actualPurch=n(actual.purchases_actual)||n(payload["اجمالي مشتريات عمانية"]),actualServ=n(actual.services_actual)||n(payload["اجمالي الخدمات المحلية"]),actualSub=n(actual.subcontracts_actual)||n(payload["اجمالي عقود الباطن"]),actualSME=actual.sme_percent??(payload["نسبة SME   "]??payload["نسبة SME"]??0),d=daysLeft(p.end_date);
 const rem=d===null?"—":d<0?'<span class="remaining late-rem">متأخر '+Math.abs(d)+' يوم</span>':d===0?'<span class="remaining late-rem">ينتهي اليوم</span>':'<span class="remaining ok-rem">'+d+' يوم</span>',sc=p.project_status==="منتهي"?"ok":p.project_status==="متعثر"?"bad":"neutral";
 const reportsHtml=re.length?re.map(r=>'<tr><td>Year '+esc(r.year_no)+' / Q'+esc(r.quarter_no)+'</td><td>'+dateFmt(r.report_date)+'</td><td><span class="report-status '+(r.status==="معتمد"?"approved":r.status==="مستلم"?"received":r.status==="مسودة"?"draft":r.status==="مرفوضة"?"rejected":r.status==="ملغي"?"cancelled":"other")+'">'+esc(r.status||"—")+'</span></td><td>'+esc(r.report_type||"—")+'</td><td>'+dateFmt(r.received_date)+'</td><td><div class="report-actions"><a class="btn" href="report-view.html?id='+encodeURIComponent(r.id)+'">استعراض</a><a class="btn ghost" href="report-form.html?id='+encodeURIComponent(id)+'&q='+encodeURIComponent(r.quarter_no||1)+'">تعديل</a></div></td></tr>').join(""):'<tr><td colspan="6"><div class="note">لا توجد تقارير مسجلة لهذا المشروع حتى الآن.</div></td></tr>';
 const planPeriod=lw[0]?("Year "+lw[0].year_no+" / Q"+lw[0].quarter_no):"—",planHtml=plan?'<div class="plan-summary"><div class="plan-box"><small>إصدار الخطة</small><b>'+esc(plan.version||"—")+'</b></div><div class="plan-box"><small>تاريخ الخطة</small><b>'+dateFmt(plan.plan_date)+'</b></div><div class="plan-box"><small>الحالة</small><b>'+esc(plan.status||"—")+'</b></div><div class="plan-box"><small>آخر فترة مخططة للعمالة</small><b>'+planPeriod+'</b></div></div>'+(plan.notes?'<div class="note" style="margin-top:10px">'+esc(plan.notes)+'</div>':""):'<div class="empty-plan">لا توجد خطة محتوى محلي مسجلة لهذا المشروع. اضغط <b>تحديث الخطة</b> لإدخال الخطة.</div>';
 const root=$("root");
 root.innerHTML='<div class="detail-head"><div><div style="margin-bottom:8px"><span class="status-large '+sc+'">'+esc(p.project_status||"غير محدد")+'</span></div><h1>'+esc(p.project_name)+'</h1><div class="meta"><span>الجهة: <b>'+esc(entity?.name||payload["الجهة الحكومية"]||"—")+'</b></span><span>المناقصة: <b>'+esc(p.tender_no||payload["رقم/نوع  المناقصة "]||"—")+'</b></span></div><div class="project-progress"><div class="line"><i style="width:'+Math.min(100,n(p.completion_percent))+'%"></i></div><div class="labels"><span>نسبة الإنجاز</span><b>'+n(p.completion_percent).toFixed(1)+'%</b></div></div></div><div class="detail-actions"><a class="btn" href="projects-live.html">العودة</a><a class="btn primary" href="plan-form.html?id='+encodeURIComponent(id)+'">تحديث الخطة</a><a class="btn primary" href="report-form.html?id='+encodeURIComponent(id)+'">+ تقرير جديد</a></div></div>'+
 '<div class="card info-card"><h2>بيانات المقاول والاستشاري والمدة</h2><div class="desc">المقاول والاستشاري والمدة في بطاقة واحدة.</div><div class="contractor-box"><div class="data-cell"><small>المقاول / الجهة المنفذة</small><b>'+esc(company?.name||payload["الجهة المنفذة"]||"—")+'</b></div><div class="data-cell"><small>الاستشاري</small><b>'+esc(p.consultant||payload["الاستشاري"]||"—")+'</b></div><div class="data-cell"><small>تاريخ البدء</small><b>'+dateFmt(p.start_date)+'</b></div><div class="data-cell"><small>تاريخ الانتهاء</small><b>'+dateFmt(p.end_date)+'</b></div><div class="data-cell"><small>المدة المتبقية</small><b>'+rem+'</b></div><div class="data-cell"><small>قيمة المشروع</small><b>'+money(p.project_value)+'</b></div><div class="data-cell"><small>المحافظة / الولاية</small><b>'+esc((p.governorate||"—")+" / "+(p.wilayat||"—"))+'</b></div><div class="data-cell"><small>قطاع العمل</small><b>'+esc(p.work_sector||"—")+'</b></div></div></div>'+
 '<div class="card compare-card section"><div class="section-head"><div><h2>الخطة مقابل الفعلي</h2><div class="desc">الأخضر = محقق، الأحمر = غير محقق.</div></div><span>المقارنة على مستوى المؤشرات الرئيسية</span></div><div class="table-wrap"><table class="compare-table"><thead><tr><th>المؤشر</th><th>الخطة</th><th>الفعلي</th><th>الفرق</th><th>الحالة</th></tr></thead><tbody>'+row("عدد العمانيين",planO,actualO,"count")+row("نسبة التعمين",planOman,actualOman,"%")+row("رواتب العمانيين",planOS,actualOS,"money")+row("رواتب الأجانب",planFS,actualFS,"money")+row("المشتريات المحلية",planPurch,actualPurch,"money")+row("الخدمات المحلية",planServ,actualServ,"money")+row("عقود الباطن",planSub,actualSub,"money")+row("SME",planSME,actualSME,"%")+'</tbody></table></div></div>'+
 '<div class="grid2 section"><div class="card"><h2>النتيجة الحالية</h2><div class="metric-row"><div class="mini"><small>العمانيون</small><b>'+actualO.toLocaleString("en-US")+'</b></div><div class="mini"><small>الأجانب</small><b>'+actualF.toLocaleString("en-US")+'</b></div><div class="mini"><small>التعمين</small><b>'+pct(actualOman)+'</b></div><div class="mini"><small>SME</small><b>'+pct(actualSME)+'</b></div></div></div><div class="card"><h2>الصرف والمحتوى المحلي</h2><div class="metric-row"><div class="mini"><small>إجمالي الصرف</small><b>'+money(actual.total_expenditure||payload["اجمالي الصرف في المشروع"])+'</b></div><div class="mini"><small>المحتوى المحلي</small><b>'+money(actual.total_local_content||payload["اجمالي المحتوى المحلي في المشروع"])+'</b></div><div class="mini"><small>المحتوى / الصرف</small><b>'+pct(actual.local_content_expenditure_percent??payload["نسبة المحتوى المحلي إلى إجمالي الصرف"])+'</b></div><div class="mini"><small>المحتوى / قيمة المشروع</small><b>'+pct(actual.local_content_project_value_percent??payload["نسبة المحتوى المحلي إلى قيمة المشروع"])+'</b></div></div></div></div>'+
 '<div class="card plan-card section"><div class="section-head"><div><h2>خطة المحتوى المحلي</h2><div class="desc">الخطة الحالية للمشروع.</div></div><a class="btn primary" href="plan-form.html?id='+encodeURIComponent(id)+'">تحديث الخطة</a></div>'+planHtml+'</div>'+
 '<div class="card reports-card section"><div class="section-head"><div><h2>التقارير</h2><div class="desc">جميع التقارير المرتبطة بالمشروع.</div></div><a class="btn primary" href="report-form.html?id='+encodeURIComponent(id)+'">+ إضافة تقرير جديد</a></div><div class="table-wrap"><table class="table"><thead><tr><th>الفترة</th><th>تاريخ التقرير</th><th>الحالة</th><th>النوع</th><th>تاريخ الاستلام</th><th>الإجراء</th></tr></thead><tbody>'+reportsHtml+'</tbody></table></div></div>'+
 '<div class="card section"><h2>ملاحظات المشروع</h2><div class="note">'+esc(payload["الملاحظات"]||"لا توجد ملاحظات مسجلة.")+'</div></div>';
 $("loading").hidden=true;root.hidden=false;
}
PTLC.ready.then(load).catch(e=>$("loading").innerHTML='<div class="alert warn"><b>تعذر تحميل المشروع</b><br>'+esc(e.message)+'</div><div style="margin-top:12px"><a class="btn primary" href="projects-live.html">العودة للمشاريع</a></div>');
})();